'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function FarmerProfilePage() {
  const [user,setUser] = useState(null);
  useEffect(() => {
    const token = localStorage.getItem('farmersetu_access_token');
    if (!token) { window.location.replace('/login'); return; }
    try {
      const saved = JSON.parse(localStorage.getItem('farmersetu_user') || 'null');
      if (!saved) { window.location.replace('/login'); return; }
      if (String(saved.role || 'farmer').toLowerCase() !== 'farmer') {
        window.location.replace('/officer/dashboard');
        return;
      }
      setUser(saved);
    } catch { window.location.replace('/login'); }
  },[]);
  const logout = () => { localStorage.removeItem('farmersetu_access_token'); localStorage.removeItem('farmersetu_user'); window.location.replace('/login'); };
  const firstName = user?.full_name?.split(' ')[0] || 'Farmer';
  const links = [['⌂','Home','/farmer/dashboard'],['◉','Farmer Profile','/farmer/profile'],['▣','Procurement Centres','/farmer/book-slot'],['▦','Book Slot','/farmer/book-slot'],['▤','My Bookings','/farmer/bookings'],['♧','Live Queue Status','/farmer/queue'],['🛒','Procurement Status','/farmer/procurement'],['▣','Payments','/farmer/payments'],['♧','Notifications','/farmer/notifications'],['◉','Help & Support','#support']];
  if (!user) return <main className="profile-loading"><div className="loading-dot"/>Loading your profile…<style jsx global>{`.profile-loading{min-height:100vh;display:grid;place-items:center;background:#f4f8f4;color:#31523c;font:600 13px Arial}.loading-dot{width:28px;height:28px;border:3px solid #d9eadc;border-top-color:#087a3e;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}`}</style></main>;
  return <main className="site-shell farmer-profile-page">
    <aside className="sidebar"><div className="brand"><img src="/images/IMG_20260829_104252_707.jpg" alt="कृषि सेतु logo" /></div><nav className="side-nav">{links.map(([icon,label,href],i)=><Link className={`nav-item ${i===1?'active':''}`} href={href} key={label}><span className="nav-icon">{icon}</span><span>{label}</span></Link>)}</nav><button className="sidebar-login profile-logout" onClick={logout}>↪ &nbsp; Logout</button><p className="copyright">© 2026 FarmerSetu</p></aside>
    <section className="content-area"><header className="topbar"><div className="location"><span className="location-pin">⌖</span><strong>FarmerSetu</strong></div><div className="top-actions"><span className="language">◎ <strong>English</strong>⌄</span><Link className="top-login" href="/farmer/profile">◉ &nbsp; {firstName}</Link></div></header>
      <div className="dashboard profile-dashboard"><section className="hero profile-hero"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">FARMERSETU • MY ACCOUNT</p><h1>Your <span>Farmer</span><br/>Profile.</h1><div className="leaf-divider"><span/><em>🌿</em><span/></div><p className="hero-copy">Manage your farmer account and keep procurement, bookings, queue and payment information in one place.</p><div className="hero-buttons"><Link href="/farmer/book-slot" className="primary-btn">▦ &nbsp; Book a Slot</Link><Link href="/farmer/bookings" className="secondary-btn">▤ &nbsp; My Bookings</Link></div></div></section>
      <section className="profile-card-main"><div className="profile-card-head"><div className="large-avatar">{firstName.charAt(0).toUpperCase()}</div><div><span className="profile-label">FARMER ACCOUNT</span><h2>{user.full_name || 'Farmer'}</h2><p>Your FarmerSetu account is active and secure</p></div><span className="active-badge">● Active</span></div><div className="profile-fields">{[['Full Name',user.full_name],['Mobile Number',user.mobile],['Email Address',user.email || 'Not provided'],['State',user.state],['District',user.district],['Role','Farmer']].map(([label,value])=><div key={label}><label>{label}</label><strong>{value || '—'}</strong></div>)}</div></section>
      <section className="quick-panel"><div><span>NEED TO VISIT A CENTRE?</span><h3>Find a nearby procurement centre</h3><p>Use your device location while booking to bring nearby centres to the top.</p></div><Link href="/farmer/book-slot">Detect location →</Link></section></div>
    </section>
    <style jsx global>{`.profile-dashboard{background:linear-gradient(180deg,#f4f8f4,#eef4ef);min-height:calc(100vh - 76px);padding-bottom:34px}.profile-hero{height:390px;border-radius:0 0 18px 18px;overflow:hidden}.profile-hero .hero-image{background-image:url('/images/rajesh-ram-HOOKgN_zIY8-unsplash.jpg')}.profile-hero .hero-content{padding-top:48px}.profile-card-main{background:#fff;border:1px solid #e1e9e2;border-radius:17px;margin:16px 0 0;box-shadow:0 10px 28px rgba(35,60,43,.06);overflow:hidden}.profile-card-head{padding:24px 27px;display:flex;align-items:center;gap:17px;border-bottom:1px solid #edf1ed}.large-avatar{width:70px;height:70px;border-radius:20px;display:grid;place-items:center;background:linear-gradient(135deg,#e8f6ea,#dcefe0);color:var(--green);font-size:28px;font-weight:900}.profile-label{font-size:9px;letter-spacing:1.5px;color:var(--green);font-weight:900}.profile-card-head h2{margin:6px 0 4px;font-size:22px}.profile-card-head p{margin:0;color:#6b756f;font-size:11px}.active-badge{margin-left:auto;background:#eaf7ed;color:#14733b;border:1px solid #cde7d3;border-radius:99px;padding:8px 12px;font-size:10px;font-weight:900}.profile-fields{display:grid;grid-template-columns:repeat(3,1fr)}.profile-fields>div{padding:20px 25px;border-right:1px solid #edf0ed;border-bottom:1px solid #edf0ed}.profile-fields>div:nth-child(3n){border-right:0}.profile-fields label{display:block;color:#7a847d;font-size:10px;margin-bottom:7px}.profile-fields strong{font-size:13px}.quick-panel{margin-top:16px;padding:18px 21px;background:linear-gradient(135deg,#eaf7ec,#f7fbf7);border:1px solid #d5e8d8;border-radius:15px;display:flex;align-items:center;justify-content:space-between;gap:18px}.quick-panel span{font-size:9px;letter-spacing:1.4px;color:#087a3e;font-weight:900}.quick-panel h3{margin:5px 0 3px;font-size:16px}.quick-panel p{margin:0;color:#6c776f;font-size:10px}.quick-panel a{flex:0 0 auto;text-decoration:none;background:#087a3e;color:#fff;padding:11px 14px;border-radius:10px;font-size:10px;font-weight:900}.profile-logout{cursor:pointer;width:calc(100% - 4px);border:1px solid #f0d8d5;background:#fff7f6;color:#9b2c22}.profile-logout:hover{background:#fff0ee}@media(max-width:900px){.profile-hero{height:450px}.profile-fields{grid-template-columns:1fr 1fr}.profile-fields>div:nth-child(3n){border-right:1px solid #edf0ed}.profile-fields>div:nth-child(2n){border-right:0}}@media(max-width:600px){.profile-fields{grid-template-columns:1fr}.profile-fields>div{border-right:0!important}.profile-card-head{align-items:flex-start;flex-wrap:wrap}.active-badge{align-self:flex-start}.profile-hero{height:420px}.quick-panel{align-items:flex-start;flex-direction:column}.quick-panel a{width:100%;text-align:center}}`}</style></main>;
}
