'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function FarmerProfilePage() {
  const [user, setUser] = useState(null);
  useEffect(() => {
    if (!localStorage.getItem('farmersetu_access_token')) { window.location.replace('/login'); return; }
    const saved = localStorage.getItem('farmersetu_user'); if (saved) { try { setUser(JSON.parse(saved)); } catch {} }
  }, []);
  const logout = () => { localStorage.removeItem('farmersetu_access_token'); localStorage.removeItem('farmersetu_user'); window.location.replace('/login'); };
  const firstName = user?.full_name?.split(' ')[0] || 'Farmer';
  const links = [['⌂','Home','/farmer/dashboard'],['◉','Farmer Profile','/farmer/profile'],['▣','Procurement Centres','#centres'],['▦','Book Slot','/farmer/book-slot'],['▤','My Bookings','/farmer/bookings'],['♧','Live Queue Status','/farmer/queue'],['🛒','Procurement Status','/farmer/procurement'],['▣','Payments','/farmer/payments'],['♧','Notifications','/farmer/notifications'],['◉','Help & Support','#support']];
  return <main className="site-shell farmer-profile-page">
    <aside className="sidebar"><div className="brand"><img src="/images/IMG_20260829_104252_707.jpg" alt="कृषि सेतु logo" /></div><nav className="side-nav">{links.map(([icon,label,href],i)=><Link className={`nav-item ${i===1?'active':''}`} href={href} key={label}><span className="nav-icon">{icon}</span><span>{label}</span></Link>)}</nav><button className="sidebar-login profile-logout" onClick={logout}>↪ &nbsp; Logout</button><p className="copyright">© 2024 Krishi Setu. All rights reserved.</p></aside>
    <section className="content-area"><header className="topbar"><div className="location"><span className="location-pin">⌖</span><strong>FarmerSetu</strong></div><div className="top-actions"><span className="language">◎ <strong>English</strong>⌄</span><Link className="top-login" href="/farmer/profile">◉ &nbsp; {firstName}</Link></div></header>
      <div className="dashboard profile-dashboard"><section className="hero profile-hero"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">FARMERSETU • MY ACCOUNT</p><h1>Your <span>Farmer</span><br/>Profile.</h1><div className="leaf-divider"><span/><em>🌿</em><span/></div><p className="hero-copy">Keep your FarmerSetu account details ready for procurement bookings, queue updates and payments.</p><div className="hero-buttons"><Link href="/farmer/book-slot" className="primary-btn">▦ &nbsp; Book a Slot</Link><Link href="/farmer/dashboard" className="secondary-btn">⌂ &nbsp; Dashboard</Link></div></div></section>
      <section className="profile-card-main"><div className="profile-card-head"><div className="large-avatar">{firstName.charAt(0).toUpperCase()}</div><div><span className="profile-label">FARMER ACCOUNT</span><h2>{user?.full_name || 'Farmer'}</h2><p>Active FarmerSetu account</p></div><span className="active-badge">● Active</span></div><div className="profile-fields">{[['Full Name',user?.full_name],['Mobile Number',user?.mobile],['Email Address',user?.email || 'Not provided'],['State',user?.state],['District',user?.district],['Role','Farmer']].map(([label,value])=><div key={label}><label>{label}</label><strong>{value || '—'}</strong></div>)}</div></section></div>
    </section><style jsx global>{`.profile-dashboard{background:#f6f8f6;min-height:calc(100vh - 76px)}.profile-hero{height:390px}.profile-hero .hero-image{background-image:url('/images/rajesh-ram-HOOKgN_zIY8-unsplash.jpg')}.profile-hero .hero-content{padding-top:48px}.profile-card-main{background:#fff;border:1px solid #e5ebe6;border-radius:15px;margin-top:16px;box-shadow:0 4px 13px rgba(35,60,43,.05);overflow:hidden}.profile-card-head{padding:22px 26px;display:flex;align-items:center;gap:17px;border-bottom:1px solid #edf0ed}.large-avatar{width:70px;height:70px;border-radius:50%;display:grid;place-items:center;background:#e7f3e6;color:var(--green);font-size:28px;font-weight:800}.profile-label{font-size:10px;letter-spacing:1.4px;color:var(--green);font-weight:800}.profile-card-head h2{margin:6px 0 4px;font-size:22px}.profile-card-head p{margin:0;color:#6b756f;font-size:12px}.active-badge{margin-left:auto;background:#eaf7ed;color:#14733b;border:1px solid #cde7d3;border-radius:99px;padding:8px 12px;font-size:11px;font-weight:800}.profile-fields{display:grid;grid-template-columns:repeat(3,1fr)}.profile-fields>div{padding:20px 25px;border-right:1px solid #edf0ed;border-bottom:1px solid #edf0ed}.profile-fields>div:nth-child(3n){border-right:0}.profile-fields label{display:block;color:#7a847d;font-size:11px;margin-bottom:7px}.profile-fields strong{font-size:14px}.profile-logout{cursor:pointer;width:calc(100% - 4px);border:1px solid #f0d8d5;background:#fff7f6;color:#9b2c22}.profile-logout:hover{background:#fff0ee}@media(max-width:900px){.profile-hero{height:450px}.profile-fields{grid-template-columns:1fr 1fr}.profile-fields>div:nth-child(3n){border-right:1px solid #edf0ed}.profile-fields>div:nth-child(2n){border-right:0}}@media(max-width:600px){.profile-fields{grid-template-columns:1fr}.profile-fields>div{border-right:0!important}.profile-card-head{align-items:flex-start;flex-wrap:wrap}.active-badge{align-self:flex-start}.profile-hero{height:420px}}`}</style></main>;
}
